### ISSUE TITLE
Can't connect to Emby via domain

### ISSUE THREAD

**Issue by Allram** [rekkyrosso/ampcast#1]
Hey,

Great app/solution!

But i can't seem to connect to my Emby instance via my Domain "https://emby.DOMAIN.org"
but if i use local ip via VPN it works, any reason to why? Is it hardcoded to only accept the Emby ports: 8096?
If i use "http://LOCALIP:8096" it works.

**Comment by rekkyrosso** [comment]
Hi Allram,

I made a slight change to the Emby login. You can try it using my test server (ampcast DOT dev).

If that doesn't fix it then I will have to investigate properly but that might take a bit longer.

**Comment by Allram** [comment]
Unfortunately got "host not found" there as well. Will try to investigate some further myself aswell :⁠-⁠)

**Comment by rekkyrosso** [comment]
Did you ever solve this problem?

**Comment by Allram** [comment]
Sorry, forgot about this.
Will test some more later today 👍

**Comment by rekkyrosso** [comment]
Can I close this issue and the associated PR? I haven't had any other reports like this.

**Comment by Allram** [comment]
Sure :⁠-⁠)
