### ISSUE TITLE
Visualization (mouseover) issue

### ISSUE THREAD

**Issue by jame25** [rekkyrosso/ampcast#10]
I've noticed a difference in behaviour of full-screen visualization when streaming from Navidrome compared to the following server: 

`https://ice6.somafm.com/dronezone-128-aac`

In the case of Navidrome streaming, mouseover causes the OSD elements to appear, but visualization itself does not stop. 

However with the above stream, mouseover full-screen visualizations stops the animation entirely for a few seconds. I use a multi-monitor setup and this problem means that I interrupt the visualization repeatedly (by accident).

To clarify; I would like to either have the above stream behave in the same way (visually) as a Navidrome stream, or perhaps even better, implement an option to lock visualization (and ignore mouseover events).

**Comment by rekkyrosso** [comment]
Can you give me a bit more info please? Which visualiser(s) and which browser are you using? I'm also not sure what you mean by "OSD elements". Googling has helped I'm afraid.

The visualizers don't respond to mouseover events, just to hide/show some UI elements, so it's likely some other problem. Interestingly, I can't get any visualizers to work with that stream. So I need to look into that that first.

**Comment by jame25** [comment]
Appologies. I am exclusively using the Windows x64 desktop app. And I can choose any of the available visualisers, they all exhibit the same behaviour. By "OSD elements" I meant the On-Screen Display text, or the UI elments as you put it.

**Comment by rekkyrosso** [comment]
I've managed to recreate your problem.

It was caused by the popout playback window trying to synch the start time. Because you were using a stream (which has an infinite duration) it was constantly reloading trying to synch. I think I've fixed the problem now and will check in a fix soon.

Thanks for reporting. That was a good one!

**Comment by rekkyrosso** [comment]
I just created a new release (version 0.9.10). Does the problem still exist?

**Comment by jame25** [comment]
Yes, the issue has been resolved. Thank you.
