### ISSUE TITLE
Search inside playlist

### ISSUE THREAD

**Issue by Pedro-Montanari** [rekkyrosso/ampcast#15]
I think an interesting QoL improvement would be the ability to search for songs inside playlists, like one would do in Apple Music and (I think?) Spotify, for example.

This helps in checking if a certain song is already in the playlist, and in narrowing down search results.

Edit: Sorry, I think I just realized this would fit better into Discussions instead of Issues

**Comment by Pedro-Montanari** [comment]
(Sorry, I think I just realized this would fit better into Discussions instead of Issues)

**Comment by rekkyrosso** [comment]
Please post this as a [discussion](https://github.com/rekkyrosso/ampcast/discussions) to keep the topic alive.
