### ISSUE TITLE
Desktop app (v0.9.9) on MacOS doesn't play music from Apple Music

### ISSUE THREAD

**Issue by sheriferson** [rekkyrosso/ampcast#16]
Version 0.9.9

Connected to Apple Music. I can play the tracks in Music.app. Ampcast lists all playlists just fine, but can't play any of the tracks.

The other connection I have is Plex, and that works fine.

https://github.com/user-attachments/assets/c8c1e256-4745-4ce0-b390-5172ad9f8c9e

**Comment by rekkyrosso** [comment]
I just created a new release (version 0.9.10). Does the problem still exist?

**Comment by sheriferson** [comment]
I was hoping to try 0.9.10, but am getting this message on app startup. I don't think I've seen this with earlier versions. Maybe something went awry with signing the app?

<img width="372" alt="Screenshot 2024-12-24 at 10 33 34 PM" src="https://github.com/user-attachments/assets/2290591c-8b6f-464e-8193-411e2a1d6045" />

**Comment by rekkyrosso** [comment]
Darn it. The build failed but looked like it passed.

I've since released version 0.9.11.

Thanks for reporting.

**Comment by sheriferson** [comment]
Works great :) Can confirm Apple Music playback is fixed too. Thanks for your work on this.

**Comment by rekkyrosso** [comment]
Thanks very much for following up.

I really appreciate your support for this project.
