### ISSUE TITLE
RPC/HTTP API?

### ISSUE THREAD

**Issue by ia74** [rekkyrosso/ampcast#5]
Hey there! I've been using ampcast for a while now, but I think that the app should have some sort of API that can for example query the currently playing song or control the player itself (play/pause/next/back/vol).
I'd like to make a [plugin for my project Freedeck](https://github.com/Freedeck/freedeck)

**Comment by rekkyrosso** [comment]
Can you post this as a [discussion](https://github.com/rekkyrosso/ampcast/discussions) instead please?
