### ISSUE TITLE
Navidrome: Sharing

### ISSUE THREAD

**Issue by jame25** [rekkyrosso/ampcast#6]
Navidrome supports the creation of a 'Share' link for an Album or individual track. Would it be at all possible to implement support for this in ampcast?

Related links: 
https://www.navidrome.org/docs/usage/sharing
https://opensubsonic.netlify.app/categories/sharing

**Comment by rekkyrosso** [comment]
Okay. I'll look into it. It doesn't seem like Navidrome incorporate this feature into their own UI. At least I couldn't find it anywhere.

**Comment by jame25** [comment]
The feature is available in the UI if: `In your configuration file, set EnableSharing=true, or set the environment variable ND_ENABLESHARING=true`

**Comment by rekkyrosso** [comment]
Added in version 0.9.10.

The links are available from the Media Info dialog.
