### ISSUE TITLE
Cover Art not showing for local media files

### ISSUE THREAD

**Issue by Pedro-Montanari** [rekkyrosso/ampcast#9]
Hello,

I normally use ampcast with Apple Music, using the Cover Art visualizer, and it works fine.

When I use cover art from local media, however, the cover does not show up.

I tried with music I purchased and downloaded from Bandcamp and from Qobuz, and the result is the same (see attached screenshot). Disabling the animated background did not make any difference.
![ampcast_3AHcCo54BA](https://github.com/user-attachments/assets/cdc9818b-0dc1-4f31-ba20-5b9cc41168d9)

For the music I purchased in Qobuz, the files are organized in this way:

```
.
└── Artist/
    └── Album/
        ├── 1/
        │   └── foo.flac
        └── cover.jpg
```

that means, the files are inside a folder called "1" and the cover, in jpg, is called "cover" and it is on the same folder level as "1".

For music I purchased on Bandcamp, the files are organized in this way:

```
.
└── Artist/
    └── Album/
        ├── foo.flac
        └── cover.jpg
```

That means the cover art is inside the Album folder.

I don't know how ampcast searcher for the cover art as of now, but maybe a search pattern could be added for example to try to find a cover called "cover" in the same folder or on a subfolder from the file path. I don't know if this is possible, as I haven't looked through the source code.

Regards,

Pedro

**Comment by rekkyrosso** [comment]
ampcast is a browser based app and as such it's not allowed to read your file system looking for images.

I can add an extra lookup in the Cover Art visualizer if the album art is missing. I can search MusicBrainz and last.fm (if you're logged in). It won't always find a match but it's better than nothing.

Alternatively, you could host your local files in a lightweight server like Subsonic and access your music through that.

**Comment by Pedro-Montanari** [comment]
I see, I actually thought about trying my own media server, I'll give Subsonic a look. Thanks for the suggestion and for the commitment!

Regards,

Pedro

**Comment by rekkyrosso** [comment]
> I can add an extra lookup in the Cover Art visualizer if the album art is missing. I can search MusicBrainz and last.fm (if you're logged in). It won't always find a match but it's better than nothing.

I added this in version 0.9.10.
